### ISSUE TITLE
modifier le nom du groupe?

### ISSUE THREAD

**Issue by guskant** [frasjbogri/cll-fr#3]
@frasjbogri Comme j'avais dit à quelques-uns de vous, "frasjbogri" n'est pas un nom correct du lojban. Êtes-vous d'accord pour modifier le nom à "faslobgri" ?

**Comment by ghost** [comment]
bien sûr.

fas-lob-gri. 
Règle CCL.1.1/4.6 ok

fraso [fas] x1 reflects French/Gallic culture/ nationality/languageinaspect x2. —Seealso{ropno}. 
lojbo [lob jbo] x1 reflects [Loglandic]/Lojbanic language/culture/nationality/communityinaspectx2. — Pre-Lojban forms of Loglan (= {dzejbo}). See also {bangu},{logji}. 
girzu [gir gri] x1 is group/cluster/team showing common property (ka) x2 due to set x3 linked by relations x4.

**Comment by guskant** [comment]
D'accord, j'ai déjà modifié le nom de l'organisation.
